apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data
  labels:
    app: airflow
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.7
    path: "/var/nfs-share/airflow"

