apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-postgres
  labels:
    app: postgres
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.7
    path: "/var/nfs-share/airflow/postgres"

