apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    name: log
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/var/airflow/logs"
