apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    name: log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: "/var/nfsshare/airflow/logs"
