apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-postgresql
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: "/var/nfsshare/airflow/postgres"

